In [4]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [5]:
# Get Data
df = pd.read_csv("./data/TwitterDataset.csv")
df.head()

,likes,parent_tweet_id,retweets,tweet_date,tweet_handle,tweet_id,tweet_text,tweet_time,tweet_url,username
0,0.0,1.366494e+18,0.0,2021-03-02,amazon,1366811295404670978,@Prinxofdarkness Thanks for contacting us back...,18:03:01,https://twitter.com/elonmusk/status/1366811295...,Prinxofdarkness
1,0.0,1.366803e+18,0.0,2021-03-02,amazon,1366805720579133444,@taliahreene We would've made the same move. üëç...,17:40:52,https://twitter.com/elonmusk/status/1366805720...,taliahreene
2,0.0,1.365764e+18,0.0,2021-03-02,amazon,1366805543382319106,@livvibarns Of course! Please keep an eye on y...,17:40:10,https://twitter.com/elonmusk/status/1366805543...,livvibarns
3,1.0,1.366783e+18,0.0,2021-03-02,amazon,1366805462952378372,@TheCleftonTwain We miss you too Sean! We miss...,17:39:51,https://twitter.com/elonmusk/status/1366805462...,TheCleftonTwain
4,2.0,1.366797e+18,0.0,2021-03-02,amazon,1366801584538140674,@taliahreene The Clash once faced the same dil...,17:24:26,https://twitter.com/elonmusk/status/1366801584...,taliahreene